### PR TITLE
Upgrade to foundation 6.1.1 & Add Babel.js ES2015

### PR DESCRIPTION
**Pull request by bsodmike**
This upgrades the foundation dependency ensuring CSS & JS work.

### CODE REVIEW

**Comment by bsodmike** [comment]
@dougmacklin hope this helps mate!

**Comment by bsodmike** [comment]
Closing for now, as I've not received any feedback; will fork this!

**Comment by bsodmike** [comment]
I've launched it separately @dougmacklin https://www.npmjs.com/package/generator-gulp-foundation-sass-babel-browserify

**Comment by dougmacklin** [comment]
Hey @bsodmike, sorry I was out of town this past weekend. Are you still interesting in merging this pull request?

**Comment by bsodmike** [comment]
Hi Doug, sorry didn't realise that. Your GitHub profile was incomplete so I
thought your account wasn't that active.

I've pushed up a fork
https://www.npmjs.com/package/generator-gulp-foundation-sass-babel-browserify

Thanks M

On Tuesday, 19 January 2016, Doug Macklin notifications@github.com wrote:

> Hey @bsodmike https://github.com/bsodmike, sorry I was out of town this
> past weekend. Are you still interesting in merging this pull request?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dougmacklin/generator-foundation-gulp-browserify/pull/2#issuecomment-172625670
> .

## 

## 

Mike's on the move!

**Comment by dougmacklin** [comment]
Thanks @bsodmike! I have updated my generator to include some of your improvements. I wanted to make sure to continue to support Foundation 5 in addition to Foundation 6 for now.

**Pull request closed without merging**
